### PR TITLE
Change attribute github urls from git:// to https://

### PR DESCRIPTION
**Pull request by ghost**
`git ls-remote` fails during a `vagrant up` if the user is stuck behind a lousy corporate firewall that doesn't support git://.

### CODE REVIEW

**Comment by ivey** [comment]
:+1:

**Comment by hostirosti** [comment]
+1

**Comment by meatballhat** [comment]
:thumbsup:

**Comment by mikesplain** [comment]
+1

**Comment by chulkilee** [comment]
:+1:

**Comment by reset** [comment]
@byggztryng could you rebase this against master so we can pull it in? Thanks!

**Comment by johnbellone** [comment]
+1

**Comment by ghost** [comment]
@reset Done!

**Comment by reset** [comment]
@byggztryng thanks so much

**Pull request merged**
