### PR TITLE
install libreadline-dev in Ubuntu & Debian so irb will work

### PR DESCRIPTION
**Pull request by cap10morgan**
IRB needs libreadline-dev installed when a Ruby is compiled for it to work. So I added it to the packages that get installed on Ubuntu and Debian.

I don't know if RedHat-style distros need this or not, I've only tested on Ubuntu 11.10.

### CODE REVIEW

**Comment by reset** [comment]
Thanks for the pull request, I'd love to help you out with this.

Theres a small issue - libreadline-dev isn't a package in the CentOS default repositories. Could you wrap this in a platform check? Only install it for Ubuntu / Debian.

Thanks!

**Comment by cap10morgan** [comment]
It is already wrapped in a platform check. It just didn't show up in the commit diff. Here's the full context:

```
when "ubuntu", "debian"
  package "build-essential"
  package "openssl"
  package "libssl-dev"
  package "libreadline-dev"
end
```

**Comment by reset** [comment]
Sorry about that, should have clicked "view file" :)

This has been released in a patch release on the community site - `1.3.1`

**Comment by cap10morgan** [comment]
No problem, and thanks for the super-fast turnaround!

**Pull request merged**
