### PR TITLE
Fix 'no such command install' error.

### PR DESCRIPTION
**Pull request by adamvaughan**
Changes the setup of ruby_build to just be an rbenv plugin just like rbenv_vars. Fixes issue #39.

### CODE REVIEW

**Comment by klevo** [comment]
:+1: tested, the fix works

**Comment by dfang** [comment]
@adamvaughan  Thanks for the fix !

**Comment by benmanns** [comment]
:+1: I was having this problem, @adamvaughan's patch fixed it.

**Comment by benmanns** [comment]
Update: this installs ruby_build as `root`:`root` instead of `node[:rbenv][:user]`:`node[:rbenv][:group]`.

**Comment by adamvaughan** [comment]
Just added a commit to correct the user and group. I went ahead and corrected rbenv_vars too.

**Comment by dfang** [comment]
why (someone) not release a new version on chef community cookbooks ?

**Comment by benmanns** [comment]
@dfang In the meantime, if you are running Berkshelf you can add

``` ruby
cookbook 'rbenv', git: 'https://github.com/adamvaughan/rbenv-cookbook.git', ref: '904a63b55a42ea9d2fa265531f860b2d1481ee8a'
```

To your `Berksfile` and run `berks update` to use @adamvaughan's pull request. That's what I'm doing and it's working well.

**Comment by dfang** [comment]
@benmanns thanks, i knew berks could download cookbooks from github, but i wish the chef community cookbooks could be updated more frequently, some cookbooks are broken ....

**Comment by fiedl** [comment]
:+1: This fixed the problem for me. +1 for pulling this. Thanks!

In the meantime, for other users of [librarian-chef](https://github.com/applicationsonline/librarian-chef):

``` ruby
# Cheffile
cookbook 'rbenv', '>=1.4.2', 
  git: 'https://github.com/adamvaughan/rbenv-cookbook', 
  ref: '904a63b55a42ea9d2fa265531f860b2d1481ee8a'
```

**Comment by fiedl** [comment]
Thanks!

**Comment by reset** [comment]
No problem, sorry for the delay. 1.5.0 has been pushed to the community site.

**Pull request merged**
