### PR TITLE
Refactored user manage_home to conform to Chef 13 syntax.

### PR DESCRIPTION
**Pull request by bemehiser**
Fixes issue described in #144

### CODE REVIEW

**Comment by PierreRambaud** [comment]
👍 +1

**Comment by bemehiser** [comment]
@PierreRambaud and anyone else who wants to use Chef 13.

I would recommend use of the [`ruby_rbenv` cookbook](https://github.com/sous-chefs/ruby_rbenv), which is a fork of the `rbenv` cookbook.

I have been unsuccessful in my attempts to update and or gain ownership of this project. In short, `rbenv` has been abandoned.

**Comment by PierreRambaud** [comment]
@bemehiser Thanks a lot for information ;)

**Comment by madwort** [comment]
Thanks for the pointer, we at transportapi have been using our own internal fork with some useful patches for us (e.g. enabling `live_stream`), will see about moving over to your fork https://github.com/RiotGamesCookbooks/rbenv-cookbook/compare/master...transportapi:master

**Pull request closed without merging**
