### PR TITLE
Adding in support for urls as patches.

### PR DESCRIPTION
**Pull request by fourseven**
Firstly this requires patchutils to be installed so that we can use
filterdiff. I’m not entirely happy with this, but is a first cut of
this functionality so happy to have a discussion over it.

Allow the rbenv_ruby LWRP to support a patch variable, which is simply
a URL that rbenv install --patch will pull in. Written in a similar
style to here.
https://github.com/sstephenson/ruby-build/wiki#make-error-for-200-p247-and-lower-on-fedorared-hat

An example is:

```
rbenv_ruby "2.1.1" do
  global true
  patch "https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/45225/diff?format=diff"
end
```

### CODE REVIEW

**Comment by fourseven** [comment]
This attempts to solve #90

**Comment by zemd** [comment]
+1 just tried this patch and it works well

**Comment by notapatch** [comment]
+1 Ruby 2.1.1 on 14.04 \* _fist pump_ *.  I hope that patched builds can be supported by rbenv-cookbook. 
Ubuntu required, as mentioned, patchutils;  `package 'patchutils'`

**Comment by reset** [comment]
@fourseven could you please update the README to reflect these changes? We need to have this functionality documented so people know it's there!

**Comment by fourseven** [comment]
Certainly @reset, just pushed that to my fork. Glad to see it's useful for others :smile:.

**Comment by reset** [comment]
@fourseven great, thank you so much

**Pull request merged**
